window.PASSPORT = {
  brand: "NIVI Passports",
  processor: "Continental Coffee",
  buyer: "European Coffee Roaster",
  destination: "Hamburg, Germany",
  product: "Arabica Green Coffee Beans",
  grade: "Plantation AA",
  quantity: "200 MT",
  po: "PO-2026-00981",
  shipment: "SHIP-2026-00081",
  batch: "CC-AR-2026-00481",
  farmId: "Farm 147",
  aiSummary: {
    verdict: "Accept Shipment",
    quality: "98%",
    euAcceptance: "99%",
    risk: "Low",
    roasting: "Excellent",
  },
  farm: {
    name: "Farm 147",
    owner: "Ramesh Gowda",
    village: "Surlabbi",
    taluk: "Somwarpet",
    district: "Kodagu",
    state: "Karnataka",
    country: "India",
    areaHa: 4.8,
    elevationM: 1125,
    variety: "Arabica S.795",
    shade: "Silver oak & pepper intercrop",
    processingIntent: "Washed (Plantation)",
    gps: { lat: 12.5974, lng: 75.8063, accuracyM: 2.1 },
    boundary: "Verified GPS polygon · 18 vertices",
    rainfall10yMm: 2100,
    soil: "Deep red lateritic, pH 6.2, high organic matter",
    historicalYieldMt: [2.1, 2.4, 2.2, 2.6, 2.5],
    previousQuality: "Plantation A / AA · Cup score 84–86",
    reliability: 96,
    verified: true,
  },
  season: {
    date: "14 Jun 2026",
    cropHealth: 95,
    expectedHarvestMt: 2.4,
    risk: "Low",
    ndvi: {
      dense: 97.37,
      moderate: 1.42,
      sparse: 1.21,
      openSoil: 0,
      cloudiness: 0,
    },
    notes: "Satellite vegetation index confirms dense canopy across the verified boundary. Localized stress patch <2% of plot.",
  },
  weather: {
    nowF: 73,
    precipitationIn: 0,
    humidity: 70,
    clouds: 52,
    windMph: 9,
    risks: 0,
    forecast: [
      { day: "Tue Jul 21", max: 79, min: 66, precip: 0.0, humidity: 68, clouds: 45, wind: 8 },
      { day: "Wed Jul 22", max: 81, min: 67, precip: 0.1, humidity: 72, clouds: 58, wind: 10 },
      { day: "Thu Jul 23", max: 78, min: 65, precip: 0.0, humidity: 70, clouds: 40, wind: 7 },
    ],
  },
  harvest: {
    date: "12 Jan 2026",
    time: "07:42 IST",
    farmer: "Ramesh Gowda",
    field: "Block A — North Slope",
    weightKg: 1840,
    moisture: 11.2,
    photos: 6,
    video: true,
    gpsVerified: true,
    ai: {
      exportQuality: "Excellent",
      specialtyGrade: "High",
      recommendation: "Premium Export",
    },
  },
  transport: {
    truckId: "KA-12-AB-4481",
    driver: "Suresh N.",
    departure: "12 Jan 2026 · 14:18",
    arrival: "12 Jan 2026 · 18:05",
    tempC: 24,
    humidity: 62,
    route: "Somwarpet → Kushalnagar → Continental Plant, Kushalnagar",
  },
  processing: {
    plant: "Continental Coffee — Kushalnagar",
    date: "13–15 Jan 2026",
    line: "Machine Line 3",
    operator: "Anita M.",
    shift: "Day A",
    steps: ["Cleaning", "Sorting", "Density separation", "Grading", "Drying", "Packing"],
    defectCount: "0.8%",
    uniformity: "High",
    aiNote: "Line 3 delivers higher yield and better bean uniformity for European premium buyers.",
  },
  lab: {
    moisture: "11.2%",
    density: "712 g/L",
    screenSize: "AA · 17/18",
    defectPct: "0.8%",
    ochratoxin: "Pass · < LOD",
    pesticides: "Pass · EU MRL",
    heavyMetals: "Pass",
    waterActivity: "0.54",
    certificateIds: ["COA-2026-1184", "PHYTO-IN-2026-8841", "COO-IN-KA-2026-2201"],
    ai: {
      euAcceptance: 99,
      rejection: 0.8,
      shelfLifeMonths: 14,
      recommendation: "Approve Shipment",
    },
  },
  pack: {
    bagIdPrefix: "BAG-CC-481",
    bags: 3200,
    palletIds: ["PLT-2026-081A", "PLT-2026-081B", "PLT-2026-081C"],
    containerId: "MSCU8842191",
  },
  warehouse: {
    location: "Continental Export Warehouse · Zone B",
    tempC: 22,
    humidity: 58,
    storageDays: 9,
    fifo: "Compliant",
    alert: null,
  },
  container: {
    number: "MSCU8842191",
    seal: "INSEAL-992184",
    loadedAt: "24 Jan 2026 · 11:40 IST",
    weightMt: 200.4,
    iot: {
      intervalMin: 30,
      lastTempC: 18.4,
      lastHumidity: 55,
      shockEvents: 0,
      doorOpenings: 0,
    },
  },
  voyage: {
    vessel: "MSC Amalfi",
    originPort: "Chennai",
    destinationPort: "Hamburg",
    position: "Arabian Sea",
    etaDays: 11,
    portCongestion: "Low",
    qualityRisk: "None",
    recommendation: "Maintain Current Route",
  },
  customs: {
    documents: [
      { name: "Commercial Invoice", status: "Linked" },
      { name: "Packing List", status: "Linked" },
      { name: "Bill of Lading", status: "Linked" },
      { name: "Certificate of Origin", status: "Valid" },
      { name: "Phytosanitary", status: "Valid" },
      { name: "Insurance", status: "Linked" },
      { name: "Inspection Reports", status: "Matched" },
    ],
    aiCheck: "Batch numbers, quantities, dates, and certificates match across all documents.",
  },
  importerVerdict: {
    shipmentMt: 200,
    origin: "Kodagu · Farm 147",
    processor: "Continental Coffee",
    processingDate: "Verified",
    quality: "98%",
    certificates: "Valid",
    currentRisk: "Low",
    roasting: "Excellent",
    recommendation: "Accept Shipment",
  },
  continentalPerformance: {
    totalShipments: 142,
    avgDelayDays: 1.4,
    avgMoisture: "11.1%",
    euAcceptance: "99.2%",
    complaints: "0.6%",
    pricePremium: "4.8%",
    recommendation: "Increase annual contract by 30%.",
  },
  riskFactors: {
    cropHealth: { value: "95%", level: "Low", note: "Dense canopy; localized NDVI stress <2% of Block A north edge" },
    ndviHeatmap: {
      densePct: 97.37,
      moderatePct: 1.42,
      sparsePct: 1.21,
      stressPatch: "Yellow/red edge on north boundary — moisture stress, not canopy failure",
    },
    diseaseAlerts: 0,
    weatherRisks: 0,
    harvestMoisture: { value: "11.2%", level: "Low", band: "Export target 10–12%" },
    labEu: { acceptancePct: 99, rejectionPct: 0.8, level: "Low", recommendation: "Approve Shipment" },
    voyageQuality: { level: "None", tempC: 18.4, humidity: 55, shock: 0, doorOpenings: 0 },
    eudr: {
      status: "Ready path",
      parcelLinked: true,
      farm: "Farm 147 Block A",
      proof: "GPS polygon 18 vertices + satellite canopy history",
    },
    carbonEstimate: {
      batchCO2eTonnes: 1.84,
      scope: "Farm gate → Hamburg",
      note: "Demo estimate from growing-season + voyage sensors",
    },
    overall: "Low",
  },
  journey: [
    { id: "farm", label: "Farm" },
    { id: "grow", label: "Grow" },
    { id: "harvest", label: "Harvest" },
    { id: "plant", label: "Plant" },
    { id: "lab", label: "Lab" },
    { id: "pack", label: "Pack" },
    { id: "ship", label: "Ship" },
    { id: "customs", label: "Customs" },
    { id: "roaster", label: "Roaster" },
  ],
};
