[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@grpc/grpc-js", "@grpc/proto-loader"]

[functions."speak"]
  timeout = 26

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Authorization, Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
